# Generated by Django 4.0.6 on 2022-12-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mylesons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyLesons',
            new_name='MyLessons',
        ),
    ]
