# Generated by Django 4.0.6 on 2022-12-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_mylesons_mylessons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mylessons',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Мои уроки'},
        ),
        migrations.AddField(
            model_name='mytable',
            name='img',
            field=models.ImageField(blank=True, upload_to='myapp/static'),
        ),
    ]
