# Generated by Django 4.0.6 on 2022-12-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_mylessons_options_mytable_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylessons',
            name='img',
            field=models.ImageField(blank=True, upload_to='myapp/static'),
        ),
    ]
